language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        -
            env: SYMFONY_VERSION=2.3.*
        -
            env: SYMFONY_VERSION=2.7.*
        -
            env: SYMFONY_VERSION=2.8.*
        -
            env: SYMFONY_VERSION=3.0.*

before_install:
    - composer self-update
    - composer --version
    - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - php php-cs-fixer.phar fix --dry-run -v
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php bin/coveralls -v
